name: playlist_app

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  share_plus: ^12.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/note.png
    - assets/images/LetitbleedRS.jpg
